/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import View.*;
import Panels.*;
import java.awt.BorderLayout;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Services.*;

/**
 *
 * @author Fabrizio
 */
public class ventanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ventanaPrincipal
     */
    public ventanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargaPanelInformativo();
        cargaFechaHora();
    }
    
    public void cargaFechaHora() {
        LocalDate now = LocalDate.now();
        Locale Regional = new Locale("es", "ES");
        LblFecha_Hora.setText(now.format(DateTimeFormatter.ofPattern("EEEE dd 'de' MMMM 'del' YYYY", Regional)));
    }
    
    public void cargaPanelInformativo() {

        PnlContenidoPaneles.setLayout(new BorderLayout());

        mostrarPaneles(new panelInformativo());
    }

    public void mostrarPaneles(JPanel panel) {

        panel.setSize(1194, 694);

        PnlContenidoPaneles.removeAll();
        PnlContenidoPaneles.add(panel, BorderLayout.CENTER);
        PnlContenidoPaneles.revalidate();
        PnlContenidoPaneles.repaint();
    }

    //NOTA: Contenido general de los servicios que ofrece el programa.
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlContenedorGeneral = new javax.swing.JPanel();
        PnlMenu = new javax.swing.JPanel();
        LblLogo = new javax.swing.JLabel();
        JSeparador01 = new javax.swing.JSeparator();
        BtnAutos = new javax.swing.JButton();
        BtnAutopartes = new javax.swing.JButton();
        BtnMantenimiento = new javax.swing.JButton();
        BtnCerrarSesion = new javax.swing.JButton();
        PnlEncabezado = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        PnlEncabezado01 = new javax.swing.JPanel();
        LblFecha_Hora = new javax.swing.JLabel();
        PnlEncabezado02 = new javax.swing.JPanel();
        LblJerarquia = new javax.swing.JLabel();
        PnlContenidoPaneles = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlMenu.setBackground(new java.awt.Color(153, 153, 153));

        LblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblLogo.setText("Imagen");

        BtnAutos.setText("AUTOS");
        BtnAutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAutosActionPerformed(evt);
            }
        });

        BtnAutopartes.setText("AUTOPARTES");
        BtnAutopartes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAutopartesActionPerformed(evt);
            }
        });

        BtnMantenimiento.setText("MANTENIMIENTO");
        BtnMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMantenimientoActionPerformed(evt);
            }
        });

        BtnCerrarSesion.setText("CERRAR SESION");
        BtnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlMenuLayout = new javax.swing.GroupLayout(PnlMenu);
        PnlMenu.setLayout(PnlMenuLayout);
        PnlMenuLayout.setHorizontalGroup(
            PnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnAutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnAutopartes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(BtnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JSeparador01)
                .addContainerGap())
        );
        PnlMenuLayout.setVerticalGroup(
            PnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlMenuLayout.createSequentialGroup()
                .addComponent(LblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JSeparador01, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnAutos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAutopartes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PnlEncabezado.setBackground(new java.awt.Color(204, 204, 204));

        LblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        LblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblTitulo.setText("TESLA");

        LblFecha_Hora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblFecha_Hora.setText("[Fecha y hora aqui]");

        javax.swing.GroupLayout PnlEncabezado01Layout = new javax.swing.GroupLayout(PnlEncabezado01);
        PnlEncabezado01.setLayout(PnlEncabezado01Layout);
        PnlEncabezado01Layout.setHorizontalGroup(
            PnlEncabezado01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlEncabezado01Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblFecha_Hora, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );
        PnlEncabezado01Layout.setVerticalGroup(
            PnlEncabezado01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlEncabezado01Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblFecha_Hora, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        LblJerarquia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblJerarquia.setText("[Nombre de Servicio]");

        javax.swing.GroupLayout PnlEncabezado02Layout = new javax.swing.GroupLayout(PnlEncabezado02);
        PnlEncabezado02.setLayout(PnlEncabezado02Layout);
        PnlEncabezado02Layout.setHorizontalGroup(
            PnlEncabezado02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlEncabezado02Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblJerarquia, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlEncabezado02Layout.setVerticalGroup(
            PnlEncabezado02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlEncabezado02Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblJerarquia, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PnlEncabezadoLayout = new javax.swing.GroupLayout(PnlEncabezado);
        PnlEncabezado.setLayout(PnlEncabezadoLayout);
        PnlEncabezadoLayout.setHorizontalGroup(
            PnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlEncabezadoLayout.createSequentialGroup()
                        .addComponent(LblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PnlEncabezado01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PnlEncabezado02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PnlEncabezadoLayout.setVerticalGroup(
            PnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addGroup(PnlEncabezadoLayout.createSequentialGroup()
                        .addComponent(PnlEncabezado01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PnlEncabezado02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PnlContenidoPaneles.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PnlContenidoPanelesLayout = new javax.swing.GroupLayout(PnlContenidoPaneles);
        PnlContenidoPaneles.setLayout(PnlContenidoPanelesLayout);
        PnlContenidoPanelesLayout.setHorizontalGroup(
            PnlContenidoPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1194, Short.MAX_VALUE)
        );
        PnlContenidoPanelesLayout.setVerticalGroup(
            PnlContenidoPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PnlContenedorGeneralLayout = new javax.swing.GroupLayout(PnlContenedorGeneral);
        PnlContenedorGeneral.setLayout(PnlContenedorGeneralLayout);
        PnlContenedorGeneralLayout.setHorizontalGroup(
            PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                .addComponent(PnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PnlEncabezado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PnlContenidoPaneles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        PnlContenedorGeneralLayout.setVerticalGroup(
            PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                .addComponent(PnlEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PnlContenidoPaneles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(PnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlContenedorGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlContenedorGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarSesionActionPerformed

        int response = JOptionPane.showConfirmDialog(null, "¿Esta seguro de salir de su sesion?", "Tesla Inc.", JOptionPane.YES_NO_OPTION);

        if (response == JOptionPane.YES_OPTION) {
            
            loginPrototipo Ventana_Login = new loginPrototipo();
            Ventana_Login.setVisible(true);
            this.setVisible(false);
        
        } else {
            //Not to programm here.
        }
    }//GEN-LAST:event_BtnCerrarSesionActionPerformed

    private void BtnAutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAutosActionPerformed
        mostrarPaneles(new panelService1());
        
        LblJerarquia.setText("SERVICIO DE VENTA DE AUTOS");
    }//GEN-LAST:event_BtnAutosActionPerformed

    private void BtnAutopartesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAutopartesActionPerformed
        mostrarPaneles(new panelService2());
        
        LblJerarquia.setText("SERVICIO DE VENTA DE AUTOPARTES");
    }//GEN-LAST:event_BtnAutopartesActionPerformed

    private void BtnMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMantenimientoActionPerformed
        mostrarPaneles(new panelService3());
        
        LblJerarquia.setText("SERVICIO DE MANTENIMIENTO DE AUTO");
    }//GEN-LAST:event_BtnMantenimientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAutopartes;
    private javax.swing.JButton BtnAutos;
    private javax.swing.JButton BtnCerrarSesion;
    private javax.swing.JButton BtnMantenimiento;
    private javax.swing.JSeparator JSeparador01;
    private javax.swing.JLabel LblFecha_Hora;
    private javax.swing.JLabel LblJerarquia;
    private javax.swing.JLabel LblLogo;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JPanel PnlContenedorGeneral;
    private javax.swing.JPanel PnlContenidoPaneles;
    private javax.swing.JPanel PnlEncabezado;
    private javax.swing.JPanel PnlEncabezado01;
    private javax.swing.JPanel PnlEncabezado02;
    private javax.swing.JPanel PnlMenu;
    // End of variables declaration//GEN-END:variables
}
