package InformativePanels;

import Panels.panelInformativo;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Fabrizio
 */
public class Informativo04 extends javax.swing.JPanel {

    /**
     * Creates new form Informativo04
     */
    public Informativo04() {
        initComponents();
    }

    public void mostrarPaneles(JPanel panel) {

        PanelContenedor.removeAll();
        PanelContenedor.add(panel, BorderLayout.CENTER);
        PanelContenedor.revalidate();
        PanelContenedor.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedor = new javax.swing.JPanel();
        TxtTitulo = new javax.swing.JLabel();
        TxtInformativo01 = new javax.swing.JLabel();
        Separador01 = new javax.swing.JSeparator();
        TxtInformativo02 = new javax.swing.JLabel();
        TxtInformativo03 = new javax.swing.JLabel();
        TxtInformativo04 = new javax.swing.JLabel();
        TxtInformativo05 = new javax.swing.JLabel();
        Separador02 = new javax.swing.JSeparator();
        TxtInformativo06 = new javax.swing.JLabel();
        TxtInformativo07 = new javax.swing.JLabel();
        TxtInformativo08 = new javax.swing.JLabel();
        Separador03 = new javax.swing.JSeparator();
        TxtInformativo09 = new javax.swing.JLabel();
        TxtInformativo10 = new javax.swing.JLabel();
        TxtInformativo11 = new javax.swing.JLabel();
        BtnRetornar = new javax.swing.JButton();
        Separador2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        TxtTitulo.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        TxtTitulo.setText("AÑO 2012 | LANZAMIENTO DEL MODEL S");

        TxtInformativo01.setText("Tesla lanza su sedán insignia, el \"Model S\", revolucionando la industria automotriz.");

        TxtInformativo02.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        TxtInformativo02.setText("· RECONOCIDO POR:");

        TxtInformativo03.setText("- Alto rendimiento y lujo.");

        TxtInformativo04.setText("- Pantalla táctil central de 17\"");

        TxtInformativo05.setText("- Autonomía de más de 500 km (según versiones).");

        TxtInformativo06.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        TxtInformativo06.setText("· PREMIOS:");

        TxtInformativo07.setText("- Auto del Año por Motor Trend (2013).");

        TxtInformativo08.setText("- Buena calificación de estrellas en seguridad.");

        TxtInformativo09.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        TxtInformativo09.setText("· IMPACTO:");

        TxtInformativo10.setText("- Eleva la imagen de Tesla como fabricante de clase mundial.");

        TxtInformativo11.setText("- Primer auto eléctrico en competir con marcas premium.");

        BtnRetornar.setText("RETORNAR");
        BtnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetornarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5.png"))); // NOI18N

        javax.swing.GroupLayout PanelContenedorLayout = new javax.swing.GroupLayout(PanelContenedor);
        PanelContenedor.setLayout(PanelContenedorLayout);
        PanelContenedorLayout.setHorizontalGroup(
            PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelContenedorLayout.createSequentialGroup()
                        .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Separador01)
                            .addComponent(Separador2)
                            .addGroup(PanelContenedorLayout.createSequentialGroup()
                                .addComponent(TxtTitulo)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(PanelContenedorLayout.createSequentialGroup()
                        .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnRetornar)
                            .addGroup(PanelContenedorLayout.createSequentialGroup()
                                .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtInformativo02)
                                    .addComponent(TxtInformativo03)
                                    .addComponent(TxtInformativo04)
                                    .addComponent(TxtInformativo05)
                                    .addComponent(TxtInformativo06)
                                    .addComponent(TxtInformativo07)
                                    .addComponent(TxtInformativo08)
                                    .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Separador03, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Separador02, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TxtInformativo01, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE))
                                    .addComponent(TxtInformativo09)
                                    .addComponent(TxtInformativo10)
                                    .addComponent(TxtInformativo11))
                                .addGap(40, 40, 40)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40))))
        );
        PanelContenedorLayout.setVerticalGroup(
            PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContenedorLayout.createSequentialGroup()
                .addComponent(TxtTitulo)
                .addGap(18, 18, 18)
                .addComponent(Separador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtInformativo01)
                .addGap(18, 18, 18)
                .addComponent(Separador01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelContenedorLayout.createSequentialGroup()
                        .addComponent(TxtInformativo02)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtInformativo03)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtInformativo04)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtInformativo05)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Separador02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(TxtInformativo06)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtInformativo07)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtInformativo08)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Separador03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(TxtInformativo09)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtInformativo10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtInformativo11))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtnRetornar)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetornarActionPerformed
        mostrarPaneles(new panelInformativo());
    }//GEN-LAST:event_BtnRetornarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRetornar;
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JSeparator Separador01;
    private javax.swing.JSeparator Separador02;
    private javax.swing.JSeparator Separador03;
    private javax.swing.JSeparator Separador2;
    private javax.swing.JLabel TxtInformativo01;
    private javax.swing.JLabel TxtInformativo02;
    private javax.swing.JLabel TxtInformativo03;
    private javax.swing.JLabel TxtInformativo04;
    private javax.swing.JLabel TxtInformativo05;
    private javax.swing.JLabel TxtInformativo06;
    private javax.swing.JLabel TxtInformativo07;
    private javax.swing.JLabel TxtInformativo08;
    private javax.swing.JLabel TxtInformativo09;
    private javax.swing.JLabel TxtInformativo10;
    private javax.swing.JLabel TxtInformativo11;
    private javax.swing.JLabel TxtTitulo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
