/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panels;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import InformativePanels.*;

/**
 *
 * @author Fabrizio
 */
public class panelInformativo extends javax.swing.JPanel {

    /**
     * Creates new form panelInformativo
     */
    public panelInformativo() {
        initComponents();
    }

    public void mostrarPaneles (JPanel panel) {
                
        panel.setSize(1194, 694);
        panel.setLocation(0,0);
        
        PnlContenedorGeneral.removeAll();
        PnlContenedorGeneral.add(panel, BorderLayout.CENTER);
        PnlContenedorGeneral.revalidate();
        PnlContenedorGeneral.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlContenedorGeneral = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        JSeparador01 = new javax.swing.JSeparator();
        LblSubtitulo = new javax.swing.JLabel();
        JSeparador02 = new javax.swing.JSeparator();
        LblEventosTesla = new javax.swing.JLabel();
        JSeparador03 = new javax.swing.JSeparator();
        LblImagen = new javax.swing.JLabel();
        LblEvento01 = new javax.swing.JLabel();
        LblAnioEvento01 = new javax.swing.JLabel();
        BtnEvento01 = new javax.swing.JButton();
        LblEvento02 = new javax.swing.JLabel();
        LblAnioEvento02 = new javax.swing.JLabel();
        BtnEvento02 = new javax.swing.JButton();
        LblEvento03 = new javax.swing.JLabel();
        LblAnioEvento03 = new javax.swing.JLabel();
        BtnEvento03 = new javax.swing.JButton();
        LblEvento04 = new javax.swing.JLabel();
        LblAnioEvento04 = new javax.swing.JLabel();
        BtnEvento04 = new javax.swing.JButton();
        LblEvento05 = new javax.swing.JLabel();
        LblAnioEvento05 = new javax.swing.JLabel();
        BtnEvento05 = new javax.swing.JButton();
        LblEvento06 = new javax.swing.JLabel();
        LblAnioEvento06 = new javax.swing.JLabel();
        BtnEvento06 = new javax.swing.JButton();
        LblEvento07 = new javax.swing.JLabel();
        LblAnioEvento07 = new javax.swing.JLabel();
        BtnEvento07 = new javax.swing.JButton();
        LblEvento08 = new javax.swing.JLabel();
        LblAnioEvento08 = new javax.swing.JLabel();
        BtnEvento08 = new javax.swing.JButton();
        JSeparador04 = new javax.swing.JSeparator();
        LblInformativo01 = new javax.swing.JLabel();
        LblInformativo02 = new javax.swing.JLabel();
        LblInformativo03 = new javax.swing.JLabel();
        LblInformativo04 = new javax.swing.JLabel();
        LblInformativo05 = new javax.swing.JLabel();

        LblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        LblTitulo.setText("TESLA, Inc. - Innovacion Electrica");

        LblSubtitulo.setText("\"Acelerando la transicion del mundo hacia la energia sostenible\"");

        LblEventosTesla.setText("EVENTOS CLAVE EN TESLA");

        LblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblImagen.setText("IMAGEN");

        LblEvento01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblEvento01.setText("Fundación de Tesla Motors por Martin Eberhard y Marc Tarpenning ...");

        LblAnioEvento01.setText("| 2003 |");

        BtnEvento01.setText("Ver mas..");
        BtnEvento01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEvento01ActionPerformed(evt);
            }
        });

        LblEvento02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblEvento02.setText("Elon Musk invierte en Tesla y se convierte en presidente de la junta ...");

        LblAnioEvento02.setText("| 2004 |");

        BtnEvento02.setText("Ver mas..");
        BtnEvento02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEvento02ActionPerformed(evt);
            }
        });

        LblEvento03.setText("Lanzamiento del Tesla Roadster, primer auto deportivo 100% eléctrico ...");

        LblAnioEvento03.setText("| 2008 |");

        BtnEvento03.setText("Ver mas..");
        BtnEvento03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEvento03ActionPerformed(evt);
            }
        });

        LblEvento04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblEvento04.setText("Lanzamiento del Model S: sedán eléctrico de alto rendimiento ...");

        LblAnioEvento04.setText("| 2012 |");

        BtnEvento04.setText("Ver mas..");
        BtnEvento04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEvento04ActionPerformed(evt);
            }
        });

        LblEvento05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblEvento05.setText("Anuncio de Powerwall: baterías para hogares ...");

        LblAnioEvento05.setText("| 2015 |");

        BtnEvento05.setText("Ver mas..");
        BtnEvento05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEvento05ActionPerformed(evt);
            }
        });

        LblEvento06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblEvento06.setText("Presentación del Tesla Semi y el Roadster de segunda generación ...");

        LblAnioEvento06.setText("| 2017 |");

        BtnEvento06.setText("Ver mas..");
        BtnEvento06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEvento06ActionPerformed(evt);
            }
        });

        LblEvento07.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblEvento07.setText("Tesla entra al S&P 500 como una de las empresas más valiosas del mundo ...");

        LblAnioEvento07.setText("| 2020 |");

        BtnEvento07.setText("Ver mas..");
        BtnEvento07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEvento07ActionPerformed(evt);
            }
        });

        LblEvento08.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblEvento08.setText("Avances en conducción autónoma y expansión global de Gigafábricas ...");

        LblAnioEvento08.setText("| 2023 |");

        BtnEvento08.setText("Ver mas..");
        BtnEvento08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEvento08ActionPerformed(evt);
            }
        });

        LblInformativo01.setText("- MODELOS DESTACADOS: Model S · Model 3 · Model X · Model Y · CyberTruck · Tesla Semi · ...");

        LblInformativo02.setText("- TECNOLOGIAS DESARROLLADAS: Auto Pilot · Full Self-Driving (FSD) · Baterias 4680 · Paneles Solares");

        LblInformativo03.setText("- ");

        LblInformativo04.setText("- ");

        LblInformativo05.setText("- ");

        javax.swing.GroupLayout PnlContenedorGeneralLayout = new javax.swing.GroupLayout(PnlContenedorGeneral);
        PnlContenedorGeneral.setLayout(PnlContenedorGeneralLayout);
        PnlContenedorGeneralLayout.setHorizontalGroup(
            PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblSubtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JSeparador01, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblEventosTesla, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JSeparador02, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                                .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(LblInformativo05, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LblInformativo04, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LblInformativo03, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LblInformativo02, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                                    .addComponent(LblInformativo01, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LblEvento07, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(JSeparador04, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JSeparador03, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PnlContenedorGeneralLayout.createSequentialGroup()
                                                .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                                                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(LblEvento05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(LblEvento04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(LblEvento03, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                                                            .addComponent(LblEvento02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(LblEvento01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                                                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(LblEvento06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(LblEvento08, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE))
                                                        .addGap(6, 6, 6)))
                                                .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                                                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(LblAnioEvento01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(LblAnioEvento02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(LblAnioEvento03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(LblAnioEvento04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(BtnEvento01)
                                                            .addComponent(BtnEvento02)
                                                            .addComponent(BtnEvento03)
                                                            .addComponent(BtnEvento04)))
                                                    .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                                                        .addComponent(LblAnioEvento05)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(BtnEvento05))
                                                    .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                                                        .addComponent(LblAnioEvento06)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(BtnEvento06))
                                                    .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                                                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(LblAnioEvento08)
                                                            .addComponent(LblAnioEvento07))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(BtnEvento07)
                                                            .addComponent(BtnEvento08))))))))
                                .addGap(121, 121, 121)
                                .addComponent(LblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 138, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PnlContenedorGeneralLayout.setVerticalGroup(
            PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JSeparador01, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblSubtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JSeparador02, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblEventosTesla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JSeparador03, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblEvento01, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblAnioEvento01, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnEvento01))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblEvento02, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblAnioEvento02, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnEvento02))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblEvento03, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblAnioEvento03, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnEvento03))
                        .addGap(12, 12, 12)
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblEvento04, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblAnioEvento04, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnEvento04))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblEvento05, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblAnioEvento05, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnEvento05))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblEvento06, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblAnioEvento06, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnEvento06))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblEvento07, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblAnioEvento07, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnEvento07))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblEvento08, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblAnioEvento08, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnEvento08)))
                    .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                        .addComponent(LblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(7, 7, 7)))
                .addComponent(JSeparador04, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblInformativo01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblInformativo02)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblInformativo03)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblInformativo04)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblInformativo05)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlContenedorGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlContenedorGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEvento01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEvento01ActionPerformed
        mostrarPaneles(new Informativo01());
    }//GEN-LAST:event_BtnEvento01ActionPerformed

    private void BtnEvento02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEvento02ActionPerformed
        mostrarPaneles(new Informativo02());
    }//GEN-LAST:event_BtnEvento02ActionPerformed

    private void BtnEvento03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEvento03ActionPerformed
        mostrarPaneles(new Informativo03());
    }//GEN-LAST:event_BtnEvento03ActionPerformed

    private void BtnEvento04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEvento04ActionPerformed
        mostrarPaneles(new Informativo04());
    }//GEN-LAST:event_BtnEvento04ActionPerformed

    private void BtnEvento05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEvento05ActionPerformed
        mostrarPaneles(new Informativo05());
    }//GEN-LAST:event_BtnEvento05ActionPerformed

    private void BtnEvento06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEvento06ActionPerformed
        mostrarPaneles(new  Informativo06());
    }//GEN-LAST:event_BtnEvento06ActionPerformed

    private void BtnEvento07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEvento07ActionPerformed
        mostrarPaneles(new Informativo07());
    }//GEN-LAST:event_BtnEvento07ActionPerformed

    private void BtnEvento08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEvento08ActionPerformed
        mostrarPaneles(new Informativo08());
    }//GEN-LAST:event_BtnEvento08ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEvento01;
    private javax.swing.JButton BtnEvento02;
    private javax.swing.JButton BtnEvento03;
    private javax.swing.JButton BtnEvento04;
    private javax.swing.JButton BtnEvento05;
    private javax.swing.JButton BtnEvento06;
    private javax.swing.JButton BtnEvento07;
    private javax.swing.JButton BtnEvento08;
    private javax.swing.JSeparator JSeparador01;
    private javax.swing.JSeparator JSeparador02;
    private javax.swing.JSeparator JSeparador03;
    private javax.swing.JSeparator JSeparador04;
    private javax.swing.JLabel LblAnioEvento01;
    private javax.swing.JLabel LblAnioEvento02;
    private javax.swing.JLabel LblAnioEvento03;
    private javax.swing.JLabel LblAnioEvento04;
    private javax.swing.JLabel LblAnioEvento05;
    private javax.swing.JLabel LblAnioEvento06;
    private javax.swing.JLabel LblAnioEvento07;
    private javax.swing.JLabel LblAnioEvento08;
    private javax.swing.JLabel LblEvento01;
    private javax.swing.JLabel LblEvento02;
    private javax.swing.JLabel LblEvento03;
    private javax.swing.JLabel LblEvento04;
    private javax.swing.JLabel LblEvento05;
    private javax.swing.JLabel LblEvento06;
    private javax.swing.JLabel LblEvento07;
    private javax.swing.JLabel LblEvento08;
    private javax.swing.JLabel LblEventosTesla;
    private javax.swing.JLabel LblImagen;
    private javax.swing.JLabel LblInformativo01;
    private javax.swing.JLabel LblInformativo02;
    private javax.swing.JLabel LblInformativo03;
    private javax.swing.JLabel LblInformativo04;
    private javax.swing.JLabel LblInformativo05;
    private javax.swing.JLabel LblSubtitulo;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JPanel PnlContenedorGeneral;
    // End of variables declaration//GEN-END:variables
}
