/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panels;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import InformativePanels.*;

/**
 *
 * @author Fabrizio
 */
public class panelInformativo extends javax.swing.JPanel {

    /**
     * Creates new form panelInformativo
     */
    public panelInformativo() {
        initComponents();
    }

    public void mostrarPaneles (JPanel panel) {
                
        panel.setSize(1194, 694);
        panel.setLocation(0,0);
        
        PanelContenedor.removeAll();
        PanelContenedor.add(panel, BorderLayout.CENTER);
        PanelContenedor.revalidate();
        PanelContenedor.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedor = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Separador01 = new javax.swing.JSeparator();
        SubTitulo01 = new javax.swing.JLabel();
        Separador02 = new javax.swing.JSeparator();
        SubTitulo02 = new javax.swing.JLabel();
        Separador03 = new javax.swing.JSeparator();
        Imagen = new javax.swing.JLabel();
        TxtInformativo01 = new javax.swing.JLabel();
        AñoTxtInformativo01 = new javax.swing.JLabel();
        BtnTxtInformativo01 = new javax.swing.JButton();
        TxtInformativo02 = new javax.swing.JLabel();
        AñoTxtInformativo02 = new javax.swing.JLabel();
        BtnTxtInformativo02 = new javax.swing.JButton();
        TxtInformativo03 = new javax.swing.JLabel();
        AñoTxtInformativo03 = new javax.swing.JLabel();
        BtnTxtInformativo03 = new javax.swing.JButton();
        TxtInformativo04 = new javax.swing.JLabel();
        AñoTxtInformativo04 = new javax.swing.JLabel();
        BtnTxtInformativo04 = new javax.swing.JButton();
        TxtInformativo05 = new javax.swing.JLabel();
        AñoTxtInformativo05 = new javax.swing.JLabel();
        BtnInformativo05 = new javax.swing.JButton();
        TxtInformativo06 = new javax.swing.JLabel();
        AñoTxtInformativo06 = new javax.swing.JLabel();
        BtnTxtInformativo06 = new javax.swing.JButton();
        TxtInformativo07 = new javax.swing.JLabel();
        AñoTxtInformativo07 = new javax.swing.JLabel();
        BtnTxtInformativo07 = new javax.swing.JButton();
        TxtInformativo08 = new javax.swing.JLabel();
        AñoTxtInformativo08 = new javax.swing.JLabel();
        BtnTxtInformativo08 = new javax.swing.JButton();
        Separador04 = new javax.swing.JSeparator();
        TxtInformativo09 = new javax.swing.JLabel();
        TxtInformativo10 = new javax.swing.JLabel();

        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Titulo.setText("TESLA, Inc. - Innovacion Electrica");

        SubTitulo01.setText("\"Acelerando la transicion del mundo hacia la energia sostenible\"");

        SubTitulo02.setText("EVENTOS CLAVE EN TESLA");

        Imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Imagen.setText("IMAGEN");

        TxtInformativo01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtInformativo01.setText("Fundación de Tesla Motors por Martin Eberhard y Marc Tarpenning ...");

        AñoTxtInformativo01.setText("| 2003 |");

        BtnTxtInformativo01.setText("Ver mas..");
        BtnTxtInformativo01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTxtInformativo01ActionPerformed(evt);
            }
        });

        TxtInformativo02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtInformativo02.setText("Elon Musk invierte en Tesla y se convierte en presidente de la junta ...");

        AñoTxtInformativo02.setText("| 2004 |");

        BtnTxtInformativo02.setText("Ver mas..");
        BtnTxtInformativo02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTxtInformativo02ActionPerformed(evt);
            }
        });

        TxtInformativo03.setText("Lanzamiento del Tesla Roadster, primer auto deportivo 100% eléctrico ...");

        AñoTxtInformativo03.setText("| 2008 |");

        BtnTxtInformativo03.setText("Ver mas..");
        BtnTxtInformativo03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTxtInformativo03ActionPerformed(evt);
            }
        });

        TxtInformativo04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtInformativo04.setText("Lanzamiento del Model S: sedán eléctrico de alto rendimiento ...");

        AñoTxtInformativo04.setText("| 2012 |");

        BtnTxtInformativo04.setText("Ver mas..");
        BtnTxtInformativo04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTxtInformativo04ActionPerformed(evt);
            }
        });

        TxtInformativo05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtInformativo05.setText("Anuncio de Powerwall: baterías para hogares ...");

        AñoTxtInformativo05.setText("| 2015 |");

        BtnInformativo05.setText("Ver mas..");
        BtnInformativo05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInformativo05ActionPerformed(evt);
            }
        });

        TxtInformativo06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtInformativo06.setText("Presentación del Tesla Semi y el Roadster de segunda generación ...");

        AñoTxtInformativo06.setText("| 2017 |");

        BtnTxtInformativo06.setText("Ver mas..");
        BtnTxtInformativo06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTxtInformativo06ActionPerformed(evt);
            }
        });

        TxtInformativo07.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtInformativo07.setText("Tesla entra al S&P 500 como una de las empresas más valiosas del mundo ...");

        AñoTxtInformativo07.setText("| 2020 |");

        BtnTxtInformativo07.setText("Ver mas..");
        BtnTxtInformativo07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTxtInformativo07ActionPerformed(evt);
            }
        });

        TxtInformativo08.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtInformativo08.setText("Avances en conducción autónoma y expansión global de Gigafábricas ...");

        AñoTxtInformativo08.setText("| 2023 |");

        BtnTxtInformativo08.setText("Ver mas..");
        BtnTxtInformativo08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTxtInformativo08ActionPerformed(evt);
            }
        });

        TxtInformativo09.setText("- MODELOS DESTACADOS: Model S · Model 3 · Model X · Model Y · CyberTruck · Tesla Semi · ...");

        TxtInformativo10.setText("- TECNOLOGIAS DESARROLLADAS: Auto Pilot · Full Self-Driving (FSD) · Baterias 4680 · Paneles Solares");

        javax.swing.GroupLayout PanelContenedorLayout = new javax.swing.GroupLayout(PanelContenedor);
        PanelContenedor.setLayout(PanelContenedorLayout);
        PanelContenedorLayout.setHorizontalGroup(
            PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SubTitulo01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelContenedorLayout.createSequentialGroup()
                        .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Separador01, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SubTitulo02, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Separador02, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelContenedorLayout.createSequentialGroup()
                                .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TxtInformativo10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                                    .addComponent(TxtInformativo09, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TxtInformativo07, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Separador04, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Separador03, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelContenedorLayout.createSequentialGroup()
                                                .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(PanelContenedorLayout.createSequentialGroup()
                                                        .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(TxtInformativo05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(TxtInformativo04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(TxtInformativo03, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                                                            .addComponent(TxtInformativo02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(TxtInformativo01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(PanelContenedorLayout.createSequentialGroup()
                                                        .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(TxtInformativo06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(TxtInformativo08, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE))
                                                        .addGap(6, 6, 6)))
                                                .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(PanelContenedorLayout.createSequentialGroup()
                                                        .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(AñoTxtInformativo01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(AñoTxtInformativo02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(AñoTxtInformativo03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(AñoTxtInformativo04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(BtnTxtInformativo01)
                                                            .addComponent(BtnTxtInformativo02)
                                                            .addComponent(BtnTxtInformativo03)
                                                            .addComponent(BtnTxtInformativo04)))
                                                    .addGroup(PanelContenedorLayout.createSequentialGroup()
                                                        .addComponent(AñoTxtInformativo05)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(BtnInformativo05))
                                                    .addGroup(PanelContenedorLayout.createSequentialGroup()
                                                        .addComponent(AñoTxtInformativo06)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(BtnTxtInformativo06))
                                                    .addGroup(PanelContenedorLayout.createSequentialGroup()
                                                        .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(AñoTxtInformativo08)
                                                            .addComponent(AñoTxtInformativo07))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(BtnTxtInformativo07)
                                                            .addComponent(BtnTxtInformativo08))))))))
                                .addGap(121, 121, 121)
                                .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 138, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelContenedorLayout.setVerticalGroup(
            PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separador01, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubTitulo01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Separador02, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubTitulo02)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Separador03, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelContenedorLayout.createSequentialGroup()
                        .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtInformativo01, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AñoTxtInformativo01, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnTxtInformativo01))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtInformativo02, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AñoTxtInformativo02, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnTxtInformativo02))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtInformativo03, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AñoTxtInformativo03, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnTxtInformativo03))
                        .addGap(12, 12, 12)
                        .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtInformativo04, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AñoTxtInformativo04, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnTxtInformativo04))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtInformativo05, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AñoTxtInformativo05, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnInformativo05))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtInformativo06, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AñoTxtInformativo06, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnTxtInformativo06))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtInformativo07, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AñoTxtInformativo07, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnTxtInformativo07))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtInformativo08, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AñoTxtInformativo08, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnTxtInformativo08)))
                    .addGroup(PanelContenedorLayout.createSequentialGroup()
                        .addComponent(Imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(7, 7, 7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Separador04, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtInformativo09)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtInformativo10)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTxtInformativo01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTxtInformativo01ActionPerformed
        mostrarPaneles(new Informativo01());
    }//GEN-LAST:event_BtnTxtInformativo01ActionPerformed

    private void BtnTxtInformativo02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTxtInformativo02ActionPerformed
        mostrarPaneles(new Informativo02());
    }//GEN-LAST:event_BtnTxtInformativo02ActionPerformed

    private void BtnTxtInformativo03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTxtInformativo03ActionPerformed
        mostrarPaneles(new Informativo03());
    }//GEN-LAST:event_BtnTxtInformativo03ActionPerformed

    private void BtnTxtInformativo04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTxtInformativo04ActionPerformed
        mostrarPaneles(new Informativo04());
    }//GEN-LAST:event_BtnTxtInformativo04ActionPerformed

    private void BtnInformativo05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInformativo05ActionPerformed
        mostrarPaneles(new Informativo05());
    }//GEN-LAST:event_BtnInformativo05ActionPerformed

    private void BtnTxtInformativo06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTxtInformativo06ActionPerformed
        mostrarPaneles(new  Informativo06());
    }//GEN-LAST:event_BtnTxtInformativo06ActionPerformed

    private void BtnTxtInformativo07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTxtInformativo07ActionPerformed
        mostrarPaneles(new Informativo07());
    }//GEN-LAST:event_BtnTxtInformativo07ActionPerformed

    private void BtnTxtInformativo08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTxtInformativo08ActionPerformed
        mostrarPaneles(new Informativo08());
    }//GEN-LAST:event_BtnTxtInformativo08ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AñoTxtInformativo01;
    private javax.swing.JLabel AñoTxtInformativo02;
    private javax.swing.JLabel AñoTxtInformativo03;
    private javax.swing.JLabel AñoTxtInformativo04;
    private javax.swing.JLabel AñoTxtInformativo05;
    private javax.swing.JLabel AñoTxtInformativo06;
    private javax.swing.JLabel AñoTxtInformativo07;
    private javax.swing.JLabel AñoTxtInformativo08;
    private javax.swing.JButton BtnInformativo05;
    private javax.swing.JButton BtnTxtInformativo01;
    private javax.swing.JButton BtnTxtInformativo02;
    private javax.swing.JButton BtnTxtInformativo03;
    private javax.swing.JButton BtnTxtInformativo04;
    private javax.swing.JButton BtnTxtInformativo06;
    private javax.swing.JButton BtnTxtInformativo07;
    private javax.swing.JButton BtnTxtInformativo08;
    private javax.swing.JLabel Imagen;
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JSeparator Separador01;
    private javax.swing.JSeparator Separador02;
    private javax.swing.JSeparator Separador03;
    private javax.swing.JSeparator Separador04;
    private javax.swing.JLabel SubTitulo01;
    private javax.swing.JLabel SubTitulo02;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel TxtInformativo01;
    private javax.swing.JLabel TxtInformativo02;
    private javax.swing.JLabel TxtInformativo03;
    private javax.swing.JLabel TxtInformativo04;
    private javax.swing.JLabel TxtInformativo05;
    private javax.swing.JLabel TxtInformativo06;
    private javax.swing.JLabel TxtInformativo07;
    private javax.swing.JLabel TxtInformativo08;
    private javax.swing.JLabel TxtInformativo09;
    private javax.swing.JLabel TxtInformativo10;
    // End of variables declaration//GEN-END:variables
}
