/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panels;

import View.*;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Fabrizio
 */
public class panelRegistro extends javax.swing.JPanel {

    /**
     * Creates new form panelRegistro
     */
    public panelRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContenedorGeneral = new javax.swing.JPanel();
        MensajeInformativo01 = new javax.swing.JLabel();
        Separador01 = new javax.swing.JSeparator();
        Imagen = new javax.swing.JLabel();
        IdentificacionDNI = new javax.swing.JLabel();
        CampoIdentificacionDNI = new javax.swing.JTextField();
        PrimerNombre = new javax.swing.JLabel();
        CampoPrimerNombre = new javax.swing.JTextField();
        SegundoNombre = new javax.swing.JLabel();
        CampoSegundoNombre = new javax.swing.JTextField();
        Apellido = new javax.swing.JLabel();
        CampoApellido = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        CampoEmail = new javax.swing.JTextField();
        NumeroPrincipal = new javax.swing.JLabel();
        CampoNumeroPrincipal = new javax.swing.JTextField();
        NumeroSecundario = new javax.swing.JLabel();
        CampoNumeroSecundario = new javax.swing.JTextField();
        Separador02 = new javax.swing.JSeparator();
        MensajeInformativo02 = new javax.swing.JLabel();
        Separador03 = new javax.swing.JSeparator();
        BotonRegistrar = new javax.swing.JButton();
        BotonRetornar = new javax.swing.JButton();

        MensajeInformativo01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MensajeInformativo01.setText("Complete all the gaps with your information to create your account:");

        Imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Imagen.setText("IMAGEN");

        IdentificacionDNI.setText("IDENTIFICATION:");

        CampoIdentificacionDNI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoIdentificacionDNI.setText("Complete the gap with your information");

        PrimerNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PrimerNombre.setText("FIRST NAME:");

        CampoPrimerNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoPrimerNombre.setText("Comple the gap with your information");

        SegundoNombre.setText("SECOND NAME:");

        CampoSegundoNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoSegundoNombre.setText("Complete the gap with your information");

        Apellido.setText("SURNAME:");

        CampoApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoApellido.setText("Complete the gap with your information");

        Email.setText("EMAIL ADDRESS:");

        CampoEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoEmail.setText("Complete the gap with your information");

        NumeroPrincipal.setText("PHONE NUMBER (MAIN):");

        CampoNumeroPrincipal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoNumeroPrincipal.setText("Complete the gap");
        CampoNumeroPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNumeroPrincipalActionPerformed(evt);
            }
        });

        NumeroSecundario.setText("PHONE NUMBER (SECONDARY):");

        CampoNumeroSecundario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoNumeroSecundario.setText("Complete the gap");

        MensajeInformativo02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MensajeInformativo02.setText("NOTE: Secondary phone number could be omitted ");

        BotonRegistrar.setText("Log In");

        BotonRetornar.setText("Return");
        BotonRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRetornarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContenedorGeneralLayout = new javax.swing.GroupLayout(ContenedorGeneral);
        ContenedorGeneral.setLayout(ContenedorGeneralLayout);
        ContenedorGeneralLayout.setHorizontalGroup(
            ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                        .addComponent(Separador01)
                        .addGap(31, 31, 31))
                    .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                        .addGroup(ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                                .addComponent(BotonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(196, 196, 196)
                                .addComponent(BotonRetornar))
                            .addGroup(ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Separador02, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                                    .addGroup(ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                                            .addComponent(NumeroSecundario)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(CampoNumeroSecundario))
                                        .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                                            .addComponent(NumeroPrincipal)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(CampoNumeroPrincipal))
                                        .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                                            .addComponent(Email)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(CampoEmail))
                                        .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                                            .addComponent(Apellido)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(CampoApellido))
                                        .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                                            .addComponent(PrimerNombre)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(CampoPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                                            .addComponent(IdentificacionDNI)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(CampoIdentificacionDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                                            .addComponent(SegundoNombre)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(CampoSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(27, 27, 27)
                                    .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 31, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorGeneralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Separador03, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorGeneralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MensajeInformativo02)
                .addGap(227, 227, 227))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorGeneralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MensajeInformativo01, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );
        ContenedorGeneralLayout.setVerticalGroup(
            ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorGeneralLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(MensajeInformativo01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separador01, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                        .addGroup(ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IdentificacionDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoIdentificacionDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PrimerNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CampoPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SegundoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CampoSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Apellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CampoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NumeroPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CampoNumeroPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NumeroSecundario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CampoNumeroSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Separador02, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MensajeInformativo02)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Separador03, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotonRetornar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContenedorGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContenedorGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CampoNumeroPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNumeroPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNumeroPrincipalActionPerformed

    private void BotonRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRetornarActionPerformed
        
        mostradorPaneles(new panelLogin());
        
    }//GEN-LAST:event_BotonRetornarActionPerformed

    public void mostradorPaneles(JPanel panel) {
        
        panel.setSize(759, 446);
        panel.setLocation(0, 0);

        ContenedorGeneral.removeAll();
        ContenedorGeneral.add(panel, BorderLayout.CENTER);
        ContenedorGeneral.revalidate();
        ContenedorGeneral.repaint();
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JButton BotonRegistrar;
    private javax.swing.JButton BotonRetornar;
    private javax.swing.JTextField CampoApellido;
    private javax.swing.JTextField CampoEmail;
    private javax.swing.JTextField CampoIdentificacionDNI;
    private javax.swing.JTextField CampoNumeroPrincipal;
    private javax.swing.JTextField CampoNumeroSecundario;
    private javax.swing.JTextField CampoPrimerNombre;
    private javax.swing.JTextField CampoSegundoNombre;
    private javax.swing.JPanel ContenedorGeneral;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel IdentificacionDNI;
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel MensajeInformativo01;
    private javax.swing.JLabel MensajeInformativo02;
    private javax.swing.JLabel NumeroPrincipal;
    private javax.swing.JLabel NumeroSecundario;
    private javax.swing.JLabel PrimerNombre;
    private javax.swing.JLabel SegundoNombre;
    private javax.swing.JSeparator Separador01;
    private javax.swing.JSeparator Separador02;
    private javax.swing.JSeparator Separador03;
    // End of variables declaration//GEN-END:variables
}
