/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panels;

import View.*;

/**
 *
 * @author Fabrizio
 */
public class panelRegistro extends javax.swing.JPanel {

    /**
     * Creates new form panelRegistro
     */
    public panelRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContenedorGeneral = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Subtitulo = new javax.swing.JLabel();
        MensajeInformativo01 = new javax.swing.JLabel();
        Separador01 = new javax.swing.JSeparator();
        PrimerNombre = new javax.swing.JLabel();
        CampoPrimerNombre = new javax.swing.JTextField();
        SegundoNombre = new javax.swing.JLabel();
        CampoSegundoNombre = new javax.swing.JTextField();
        IdentificacionDNI = new javax.swing.JLabel();
        CampoIdentificacionDNI = new javax.swing.JTextField();
        Apellido = new javax.swing.JLabel();
        CampoApellido = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        CampoEmail = new javax.swing.JTextField();
        NumeroPrincipal = new javax.swing.JLabel();
        CampoNumeroPrincipal = new javax.swing.JTextField();
        NumeroSecundario = new javax.swing.JLabel();
        CampoNumeroSecundario = new javax.swing.JTextField();
        Separador02 = new javax.swing.JSeparator();
        MensajeInformativo02 = new javax.swing.JLabel();
        Separador03 = new javax.swing.JSeparator();
        BotonRegistrar = new javax.swing.JButton();
        BotonRetornar = new javax.swing.JButton();

        Encabezado.setBackground(new java.awt.Color(204, 204, 204));

        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("TESLA");

        Subtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Subtitulo.setText("Log In Section");

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Subtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Subtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        MensajeInformativo01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MensajeInformativo01.setText("Complete all the gaps with your information to create your account:");

        PrimerNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PrimerNombre.setText("FIRST NAME:");

        CampoPrimerNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoPrimerNombre.setText("Comple the gap with your information");

        SegundoNombre.setText("SECOND NAME:");

        CampoSegundoNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoSegundoNombre.setText("Complete the gap with your information");

        IdentificacionDNI.setText("IDENTIFICATION:");

        CampoIdentificacionDNI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoIdentificacionDNI.setText("Complete the gap with your information");

        Apellido.setText("SURNAME:");

        CampoApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoApellido.setText("Complete the gap with your information");

        Email.setText("EMAIL ADDRESS:");

        CampoEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoEmail.setText("Complete the gap with your information");

        NumeroPrincipal.setText("PHONE NUMBER (MAIN):");

        CampoNumeroPrincipal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoNumeroPrincipal.setText("Complete the gap");
        CampoNumeroPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNumeroPrincipalActionPerformed(evt);
            }
        });

        NumeroSecundario.setText("PHONE NUMBER (SECONDARY):");

        CampoNumeroSecundario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoNumeroSecundario.setText("Complete the gap");

        MensajeInformativo02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MensajeInformativo02.setText("NOTE: Secondary phone number could be omitted ");

        BotonRegistrar.setText("Log In");

        BotonRetornar.setText("Return");
        BotonRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRetornarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContenedorGeneralLayout = new javax.swing.GroupLayout(ContenedorGeneral);
        ContenedorGeneral.setLayout(ContenedorGeneralLayout);
        ContenedorGeneralLayout.setHorizontalGroup(
            ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorGeneralLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorGeneralLayout.createSequentialGroup()
                        .addGroup(ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Separador01, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                            .addComponent(Separador02)
                            .addComponent(Separador03))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorGeneralLayout.createSequentialGroup()
                        .addComponent(BotonRetornar)
                        .addContainerGap())))
            .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                .addGroup(ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(MensajeInformativo01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                                .addComponent(NumeroSecundario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoNumeroSecundario))
                            .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                                .addComponent(NumeroPrincipal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoNumeroPrincipal))
                            .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                                .addComponent(Email)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoEmail))
                            .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                                .addComponent(Apellido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoApellido))
                            .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                                .addComponent(PrimerNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                                .addComponent(IdentificacionDNI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoIdentificacionDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                                .addComponent(SegundoNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoSegundoNombre)))
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                        .addGroup(ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(MensajeInformativo02, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(BotonRegistrar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ContenedorGeneralLayout.setVerticalGroup(
            ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                .addComponent(Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MensajeInformativo01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Separador01, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdentificacionDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoIdentificacionDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PrimerNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CampoPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SegundoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CampoSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Apellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CampoApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CampoEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NumeroPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CampoNumeroPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NumeroSecundario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CampoNumeroSecundario, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Separador02, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MensajeInformativo02)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Separador03, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonRegistrar)
                .addGap(18, 18, 18)
                .addComponent(BotonRetornar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContenedorGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContenedorGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CampoNumeroPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNumeroPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNumeroPrincipalActionPerformed

    private void BotonRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRetornarActionPerformed
        
        loginPrototipo ventana_login = new loginPrototipo();
        
        ventana_login.setVisible(true);
        
    }//GEN-LAST:event_BotonRetornarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JButton BotonRegistrar;
    private javax.swing.JButton BotonRetornar;
    private javax.swing.JTextField CampoApellido;
    private javax.swing.JTextField CampoEmail;
    private javax.swing.JTextField CampoIdentificacionDNI;
    private javax.swing.JTextField CampoNumeroPrincipal;
    private javax.swing.JTextField CampoNumeroSecundario;
    private javax.swing.JTextField CampoPrimerNombre;
    private javax.swing.JTextField CampoSegundoNombre;
    private javax.swing.JPanel ContenedorGeneral;
    private javax.swing.JLabel Email;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JLabel IdentificacionDNI;
    private javax.swing.JLabel MensajeInformativo01;
    private javax.swing.JLabel MensajeInformativo02;
    private javax.swing.JLabel NumeroPrincipal;
    private javax.swing.JLabel NumeroSecundario;
    private javax.swing.JLabel PrimerNombre;
    private javax.swing.JLabel SegundoNombre;
    private javax.swing.JSeparator Separador01;
    private javax.swing.JSeparator Separador02;
    private javax.swing.JSeparator Separador03;
    private javax.swing.JLabel Subtitulo;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
