/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panels;

import DatabaseModels.Cliente;
import Interfaces.DAOCliente;
import Model.DAOClienteIMPLEMENT;
import View.*;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Fabrizio
 */
public class panelRegistro extends javax.swing.JPanel {

    /**
     * Creates new form panelRegistro
     */
    public panelRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlContenedorGeneral = new javax.swing.JPanel();
        LblIndicaciones = new javax.swing.JLabel();
        JSeparador01 = new javax.swing.JSeparator();
        LblLogo = new javax.swing.JLabel();
        LblIdentificacionDNI = new javax.swing.JLabel();
        JTFIdentificacionDNI = new javax.swing.JTextField();
        LblPrimerNombre = new javax.swing.JLabel();
        JTFPrimerNombre = new javax.swing.JTextField();
        LblSegundoNombre = new javax.swing.JLabel();
        JTFSegundoNombre = new javax.swing.JTextField();
        LblApellido = new javax.swing.JLabel();
        JTFApellido = new javax.swing.JTextField();
        LblEmail = new javax.swing.JLabel();
        JTFEmail = new javax.swing.JTextField();
        LblNumeroPrincipal = new javax.swing.JLabel();
        JTFNumeroPrincipal = new javax.swing.JTextField();
        LblNumeroSecundario = new javax.swing.JLabel();
        JTFNumeroSecundario = new javax.swing.JTextField();
        JSeparador02 = new javax.swing.JSeparator();
        LblNotaInformativa = new javax.swing.JLabel();
        JSeparador03 = new javax.swing.JSeparator();
        BtnRegistrarse = new javax.swing.JButton();
        BtnRetornar = new javax.swing.JButton();

        LblIndicaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblIndicaciones.setText("Complete all the gaps with your information to create your account:");

        LblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblLogo.setText("IMAGEN");

        LblIdentificacionDNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblIdentificacionDNI.setText("IDENTIFICATION:");

        JTFIdentificacionDNI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFIdentificacionDNI.setText("Complete the gap with your information");

        LblPrimerNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblPrimerNombre.setText("FIRST NAME:");

        JTFPrimerNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFPrimerNombre.setText("Comple the gap with your information");

        LblSegundoNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblSegundoNombre.setText("SECOND NAME:");

        JTFSegundoNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFSegundoNombre.setText("Complete the gap with your information");

        LblApellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblApellido.setText("SURNAME:");

        JTFApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFApellido.setText("Complete the gap with your information");

        LblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblEmail.setText("EMAIL ADDRESS:");

        JTFEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFEmail.setText("Complete the gap with your information");
        JTFEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFEmailActionPerformed(evt);
            }
        });

        LblNumeroPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblNumeroPrincipal.setText("PHONE NUMBER (MAIN):");

        JTFNumeroPrincipal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFNumeroPrincipal.setText("Complete the gap");
        JTFNumeroPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNumeroPrincipalActionPerformed(evt);
            }
        });

        LblNumeroSecundario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblNumeroSecundario.setText("PHONE NUMBER (SECONDARY):");

        JTFNumeroSecundario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFNumeroSecundario.setText("Complete the gap");

        LblNotaInformativa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblNotaInformativa.setText("NOTE: Secondary phone number could be omitted ");

        BtnRegistrarse.setText("Log In");
        BtnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarseActionPerformed(evt);
            }
        });

        BtnRetornar.setText("VOLVER");
        BtnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetornarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlContenedorGeneralLayout = new javax.swing.GroupLayout(PnlContenedorGeneral);
        PnlContenedorGeneral.setLayout(PnlContenedorGeneralLayout);
        PnlContenedorGeneralLayout.setHorizontalGroup(
            PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlContenedorGeneralLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(237, 237, 237)
                        .addComponent(BtnRetornar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlContenedorGeneralLayout.createSequentialGroup()
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblIndicaciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JSeparador01))
                        .addGap(31, 31, 31))
                    .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LblNotaInformativa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JSeparador02, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                                .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(LblIdentificacionDNI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(LblSegundoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(LblPrimerNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(LblApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(LblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JTFApellido)
                                            .addComponent(JTFSegundoNombre)
                                            .addComponent(JTFIdentificacionDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                            .addComponent(JTFPrimerNombre)
                                            .addComponent(JTFEmail)))
                                    .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(LblNumeroSecundario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(LblNumeroPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JTFNumeroPrincipal)
                                            .addComponent(JTFNumeroSecundario))))
                                .addGap(27, 27, 27)
                                .addComponent(LblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JSeparador03))
                        .addGap(0, 30, Short.MAX_VALUE))))
        );
        PnlContenedorGeneralLayout.setVerticalGroup(
            PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlContenedorGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblIndicaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JSeparador01, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblIdentificacionDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFIdentificacionDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LblPrimerNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JTFPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LblSegundoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JTFSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LblApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JTFApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LblNumeroPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JTFNumeroPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LblNumeroSecundario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JTFNumeroSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JSeparador02, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblNotaInformativa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JSeparador03, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                        .addComponent(BtnRegistrarse)
                        .addGap(27, 27, 27))
                    .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnRetornar)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlContenedorGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlContenedorGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JTFNumeroPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNumeroPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFNumeroPrincipalActionPerformed

    private void BtnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetornarActionPerformed

        mostradorPaneles(new panelLogin());

    }//GEN-LAST:event_BtnRetornarActionPerformed

    private void BtnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarseActionPerformed

        //Registro de usuario-cliente:
        String identificacionDNI = JTFIdentificacionDNI.getText();
        String primerNombre = JTFPrimerNombre.getText();
        String segundoNombre = JTFSegundoNombre.getText();
        String apellido = JTFApellido.getText();
        String email = JTFEmail.getText();
        String primerTelefono = JTFNumeroPrincipal.getText();
        String segundoTelefono = JTFNumeroSecundario.getText();

        //Parametrizacion de campos:
        if (JTFIdentificacionDNI.equals("Ingrese su DNI.") || JTFPrimerNombre.equals("Ingrese su primer nombre.") || JTFSegundoNombre.equals("Ingrese su segundo nombre.")
                || JTFApellido.equals("Ingrese su apellido.") || JTFEmail.equals("Ingrese la direccion de correo electronico") || JTFNumeroPrincipal.equals("Ingrese su primer numero.")
                || JTFNumeroSecundario.equals("Ingrese su segunod numero telefonico")) {
            JOptionPane.showMessageDialog(null, "Por favor, asegurese de que todos los campos estan completos, Gracias.", "Tesla", JOptionPane.WARNING_MESSAGE);
            //Redireccion el cursor al cuadro de texto "txtFldNombre_RegistroUsuarioPanel"
            JTFIdentificacionDNI.requestFocus();
            return;
        }

        try {
            Cliente cliente = new Cliente();
            cliente.setDNI_Cliente(identificacionDNI);
            cliente.setNombre_Cliente(primerNombre);
            cliente.setSegundoNombre_Cliente(segundoNombre);
            cliente.setApellido_Cliente(apellido);
            cliente.setCorreo_Cliente(email);
            cliente.setTelefono_Cliente(primerTelefono);
            cliente.setSegundoTelefono_Cliente(segundoTelefono);

            DAOCliente daoCl = new DAOClienteIMPLEMENT();
            daoCl.registrar(cliente);

            System.out.println("Se ha registrado correctamente.");

        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }

        ventanaPrincipal Ventana_Principal = new ventanaPrincipal();
        Ventana_Principal.setVisible(true);

    }//GEN-LAST:event_BtnRegistrarseActionPerformed

    private void JTFEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFEmailActionPerformed

    public void mostradorPaneles(JPanel panel) {

        panel.setSize(759, 446);
        panel.setLocation(0, 0);

        PnlContenedorGeneral.removeAll();
        PnlContenedorGeneral.add(panel, BorderLayout.CENTER);
        PnlContenedorGeneral.revalidate();
        PnlContenedorGeneral.repaint();

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistrarse;
    private javax.swing.JButton BtnRetornar;
    private javax.swing.JSeparator JSeparador01;
    private javax.swing.JSeparator JSeparador02;
    private javax.swing.JSeparator JSeparador03;
    private javax.swing.JTextField JTFApellido;
    private javax.swing.JTextField JTFEmail;
    private javax.swing.JTextField JTFIdentificacionDNI;
    private javax.swing.JTextField JTFNumeroPrincipal;
    private javax.swing.JTextField JTFNumeroSecundario;
    private javax.swing.JTextField JTFPrimerNombre;
    private javax.swing.JTextField JTFSegundoNombre;
    private javax.swing.JLabel LblApellido;
    private javax.swing.JLabel LblEmail;
    private javax.swing.JLabel LblIdentificacionDNI;
    private javax.swing.JLabel LblIndicaciones;
    private javax.swing.JLabel LblLogo;
    private javax.swing.JLabel LblNotaInformativa;
    private javax.swing.JLabel LblNumeroPrincipal;
    private javax.swing.JLabel LblNumeroSecundario;
    private javax.swing.JLabel LblPrimerNombre;
    private javax.swing.JLabel LblSegundoNombre;
    private javax.swing.JPanel PnlContenedorGeneral;
    // End of variables declaration//GEN-END:variables
}
