/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Services;

import Panels.panelInformativo;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import AutosPanel.*;

/**
 *
 * @author Fabrizio
 */
public class panelService1 extends javax.swing.JPanel {

    /**
     * Creates new form panelAutos
     */
    public panelService1() {
        initComponents();
        configuracionEventosTabla();
        cargaDatosPrueba();
    }
    
    public void filtradoGeneral() {
        //NOTA: Codigo implementable, pero la base de datos debe estar en ejecucion:
        /*
            String año = cbxAño.getSelectedItem().toString();
    String tipo = cbxTipo.getSelectedItem().toString();
    String precio = cbxPrecio.getSelectedItem().toString();
        
    String sql = "SELECT * FROM vehiculos WHERE 1=1";

    if (!año.equals("Todos")) {
        sql += " AND año = '" + año + "'";
    }

    if (!tipo.equals("Todos")) {
        sql += " AND tipo = '" + tipo + "'";
    }

    if (!precio.equals("Todos")) {
        switch (precio) {
            case "Menos de 15,000" -> sql += " AND precio < 15000";
            case "15,000 - 25,000" -> sql += " AND precio BETWEEN 15000 AND 25000";
            case "Más de 25,000" -> sql += " AND precio > 25000";
        }
    }

    // Ejecutar la consulta
    try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tu_bd", "usuario", "clave");
         Statement stmt = con.createStatement();
         ResultSet rs = stmt.executeQuery(sql)) {

        DefaultTableModel modelo = (DefaultTableModel) tablaVehiculos.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        while (rs.next()) {
            modelo.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("marca"),
                rs.getString("modelo"),
                rs.getInt("año"),
                rs.getDouble("precio"),
                rs.getString("tipo")
            });
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al consultar: " + e.getMessage());
    }
         */
    }

    public void filtrosVehiculo() {
        CbxAñoVehiculo.addActionListener(e -> filtrosVehiculo());
        CbxTipoVehiculo.addActionListener(e -> filtrosVehiculo());
        CbxPrecioVehiculo.addActionListener(e -> filtrosVehiculo());
    }

    public void configuracionEventosTabla() {
        TblVehiculos.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int fila = TblVehiculos.getSelectedRow();
                if (fila != -1) {
                    String marca = TblVehiculos.getValueAt(fila, 1).toString();
                    String modelo = TblVehiculos.getValueAt(fila, 2).toString();
                    String anio = TblVehiculos.getValueAt(fila, 3).toString();
                    String precio = TblVehiculos.getValueAt(fila, 4).toString();

                    mostrarPaneles(new Auto01());

                    /*
                    String rutaImagen = obtenerRutaImagen(modelo); // Puedes usar el modelo como identificador
                    panelDetalle.cargarDatos(marca, modelo, anio, precio, rutaImagen);
                    layout.show(contenedorPaneles, "panelDetalle");
                     */
                }
            }
        });
    }

    public void cargaDatosPrueba() {
        //Datos de prueba, no utilizar al momento de la implementacio de la base de datos SQL original.
        DefaultTableModel modelo = (DefaultTableModel) TblVehiculos.getModel();
        modelo.setRowCount(0); // Limpia las filas existentes

        modelo.addRow(new Object[]{"001", "Tesla", "01", "2025", "12000"});
        modelo.addRow(new Object[]{"002", "Tesla", "02", "2015", "35000"});
        modelo.addRow(new Object[]{"003", "Tesla", "03", "2005", "4550"});
        modelo.addRow(new Object[]{"004", "Tesla", "04", "2013", "22390"});

    }

    public void mostrarPaneles(JPanel panel) {
        panel.setSize(1194, 694);
        panel.setLocation(0, 0);

        PanelContenedor.removeAll();
        PanelContenedor.add(panel, BorderLayout.CENTER);
        PanelContenedor.revalidate();
        PanelContenedor.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedor = new javax.swing.JPanel();
        TxtTitulo = new javax.swing.JLabel();
        TxtSubtitulo = new javax.swing.JLabel();
        Separador01 = new javax.swing.JSeparator();
        TxtBusquedaVehiculo = new javax.swing.JTextField();
        BtnBusquedaVehiculo = new javax.swing.JButton();
        TxtInformativo01 = new javax.swing.JLabel();
        TxtInformativo02 = new javax.swing.JLabel();
        CbxAñoVehiculo = new javax.swing.JComboBox<>();
        TxtInformativo03 = new javax.swing.JLabel();
        CbxTipoVehiculo = new javax.swing.JComboBox<>();
        TxtInformativo04 = new javax.swing.JLabel();
        CbxPrecioVehiculo = new javax.swing.JComboBox<>();
        Separador02 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblVehiculos = new javax.swing.JTable();
        Separador03 = new javax.swing.JSeparator();
        BtnRetornar = new javax.swing.JButton();
        BtnDetalles = new javax.swing.JButton();

        TxtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        TxtTitulo.setText("VEHICULOS DISPONIBLES");

        TxtSubtitulo.setText("Busque el vehiculo de su preferencia:");

        TxtBusquedaVehiculo.setText("Ingrese el nombre o modelo especifico del vehiculo que busca.");

        BtnBusquedaVehiculo.setText("BUSCAR");
        BtnBusquedaVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBusquedaVehiculoActionPerformed(evt);
            }
        });

        TxtInformativo01.setText("Filtrar por:");

        TxtInformativo02.setText("AÑO:");

        CbxAñoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "2025", "2024", "2023" }));

        TxtInformativo03.setText("TIPO:");

        CbxTipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "SEDAN", "SUV", "CAMIONETA" }));

        TxtInformativo04.setText("PRECIO:");

        CbxPrecioVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "MENOS DE 15,000", "15,000 - 25,000", "MAS DE 25,000" }));
        CbxPrecioVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxPrecioVehiculoActionPerformed(evt);
            }
        });

        TblVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Marca", "Modelo", "Año", "Precio"
            }
        ));
        jScrollPane1.setViewportView(TblVehiculos);

        BtnRetornar.setText("RETORNAR");
        BtnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetornarActionPerformed(evt);
            }
        });

        BtnDetalles.setText("VER MAS..");

        javax.swing.GroupLayout PanelContenedorLayout = new javax.swing.GroupLayout(PanelContenedor);
        PanelContenedor.setLayout(PanelContenedorLayout);
        PanelContenedorLayout.setHorizontalGroup(
            PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Separador03)
                    .addComponent(Separador02)
                    .addComponent(Separador01)
                    .addGroup(PanelContenedorLayout.createSequentialGroup()
                        .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtSubtitulo)
                            .addGroup(PanelContenedorLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(TxtBusquedaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnBusquedaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(TxtInformativo01)
                                .addGap(18, 18, 18)
                                .addComponent(TxtInformativo02)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CbxAñoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtInformativo03)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CbxTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtInformativo04)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CbxPrecioVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelContenedorLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(PanelContenedorLayout.createSequentialGroup()
                        .addComponent(BtnRetornar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnDetalles)))
                .addContainerGap())
        );
        PanelContenedorLayout.setVerticalGroup(
            PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtSubtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Separador01, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnBusquedaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtInformativo01, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtInformativo02, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CbxAñoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtInformativo03, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CbxTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtInformativo04, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CbxPrecioVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TxtBusquedaVehiculo))
                .addGap(18, 18, 18)
                .addComponent(Separador02, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Separador03, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRetornar)
                    .addComponent(BtnDetalles))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetornarActionPerformed
        mostrarPaneles(new panelInformativo());
    }//GEN-LAST:event_BtnRetornarActionPerformed

    private void BtnBusquedaVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBusquedaVehiculoActionPerformed
        //NOTA: Sistema de busqueda que evalue si el campo de JTxtField esta lleno buscar con esa informacion
        //      o si los ComboBox estan seleccionados buscar con esos parametros.
        try {

        } catch (Exception e) {

        }
    }//GEN-LAST:event_BtnBusquedaVehiculoActionPerformed

    private void CbxPrecioVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxPrecioVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxPrecioVehiculoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBusquedaVehiculo;
    private javax.swing.JButton BtnDetalles;
    private javax.swing.JButton BtnRetornar;
    private javax.swing.JComboBox<String> CbxAñoVehiculo;
    private javax.swing.JComboBox<String> CbxPrecioVehiculo;
    private javax.swing.JComboBox<String> CbxTipoVehiculo;
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JSeparator Separador01;
    private javax.swing.JSeparator Separador02;
    private javax.swing.JSeparator Separador03;
    private javax.swing.JTable TblVehiculos;
    private javax.swing.JTextField TxtBusquedaVehiculo;
    private javax.swing.JLabel TxtInformativo01;
    private javax.swing.JLabel TxtInformativo02;
    private javax.swing.JLabel TxtInformativo03;
    private javax.swing.JLabel TxtInformativo04;
    private javax.swing.JLabel TxtSubtitulo;
    private javax.swing.JLabel TxtTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
