/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Services;

import DatabaseModels.ReservaServTres;
import DatabaseModels.Sesion;
import Interfaces.DAOReservaServTres;
import Model.DAOReservaServTresIMPLEMENT;
import Panels.panelInformativo;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLaf;
import java.awt.BorderLayout;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.time.LocalDate;
import javax.swing.JPanel;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.FlatClientProperties;
import javax.swing.*;

/**
 *
 * @author Fabrizio
 */
public class panelService3 extends javax.swing.JPanel {

    /**
     * Creates new form panelService3
     */
    public panelService3() {
        initComponents();
        //TblFechasContenido.setEnabled(false);
        //TxtPrecio.setText("00.0");
        actualizarEstadoCampos();
        //contenedorPRecio.setEnabled(false);
        JTFContenedorPrecio.setText("0.00");
        JTFContenedorPrecio.setEditable(false);
        estilosPanelService03();
    }

    public void mostrarPaneles(JPanel panel) {
        panel.setSize(1194, 694);
        panel.setLocation(0, 0);

        PnlContenedorGeneral.removeAll();
        PnlContenedorGeneral.add(panel, BorderLayout.CENTER);
        PnlContenedorGeneral.revalidate();
        PnlContenedorGeneral.repaint();
    }

    public void estilosPanelService03() {
        JTFServicioTesla02.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Ingrese su nombre");
        JTFServicioTesla03.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Ingrese campo tesla 2");
        JTFServicioTesla03.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Ingrese campo tesla 3");
    }

    /*
    
    
     */
    public void fechasProgramadas() {

        /*
        //NOTA: Antes de implementar el metodo, buscar la forma en la cual la fecha adquiera diferentes
        //      valores, no solo uno parametrizado.
        // Obten el modelo de tu tabla
        DefaultTableModel model = (DefaultTableModel) TblFechasContenido.getModel();

        // Limpia la tabla por si tenia datos anteriores
        model.setRowCount(0);

        // --- EJEMPLO DE CÓMO AGREGAR UNA FILA CON UNA FECHA ESPECÍFICA ---
        // 1. Crea la fecha que necesites (Año, Mes, Día)
        LocalDate fechaMantenimiento = LocalDate.of(2025, 5, 20);

        // 2. Crea un formateador para mostrar la fecha como "día/mes/año"
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        // 3. Convierte la fecha a un String con el formato deseado
        String fechaFormateada = fechaMantenimiento.format(formatter);

        // 4. Agrega la fila a la tabla con la fecha ya formateada
        //NOTA: Por analizar ya que debe estar en relacion con otras tablas.
        model.addRow(new Object[]{
            "M001", // ID
            "AUT-123", // IDAuto
            "EMP-01", // IDEmpleado
            fechaFormateada, // Fecha (String)
            "Cambio de aceite sintético", // Descripción
            250.00 // Costo
        });

        /*
        // --- OTRO EJEMPLO CON LA FECHA ACTUAL ---
        LocalDate fechaActual = LocalDate.now();
        String fechaActualFormateada = fechaActual.format(formatter);
        model.addRow(new Object[]{
            "M002", "AUT-456", "EMP-02", fechaActualFormateada, "Revisión de neumáticos", 80.00
        });
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlContenedorGeneral = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        LblSubtitulo = new javax.swing.JLabel();
        JSeparador01 = new javax.swing.JSeparator();
        LblSeleccionarModelo = new javax.swing.JLabel();
        CbxSeleccionarTipoAuto = new javax.swing.JComboBox<>();
        LblNotaInformativa = new javax.swing.JLabel();
        JSeparador02 = new javax.swing.JSeparator();
        LblCategoriaTesla = new javax.swing.JLabel();
        JSeparador03 = new javax.swing.JSeparator();
        LblServicioTesla01 = new javax.swing.JLabel();
        CbxServicioTesla01 = new javax.swing.JComboBox<>();
        LblServicioTesla02 = new javax.swing.JLabel();
        JTFServicioTesla02 = new javax.swing.JTextField();
        LblServicioTesla03 = new javax.swing.JLabel();
        JTFServicioTesla03 = new javax.swing.JTextField();
        LblServicioTesla04 = new javax.swing.JLabel();
        JTFServicioTesla04 = new javax.swing.JTextField();
        LblServicioTesla05 = new javax.swing.JLabel();
        JTFServicioTesla05 = new javax.swing.JTextField();
        LblServicioTesla06 = new javax.swing.JLabel();
        JTFServicioTesla06 = new javax.swing.JTextField();
        LblCategoriaOtro = new javax.swing.JLabel();
        JSeparador04 = new javax.swing.JSeparator();
        LblServicioOtro01 = new javax.swing.JLabel();
        CbxServicioOtro01 = new javax.swing.JComboBox<>();
        LblServicioOtro02 = new javax.swing.JLabel();
        JTFServicioOtro02 = new javax.swing.JTextField();
        LblServicioOtro03 = new javax.swing.JLabel();
        JTFServicioOtro03 = new javax.swing.JTextField();
        LblServicioOtro04 = new javax.swing.JLabel();
        JTFServicioOtro04 = new javax.swing.JTextField();
        LblServicioOtro05 = new javax.swing.JLabel();
        JTFServicioOtro05 = new javax.swing.JTextField();
        LblServicioOtro06 = new javax.swing.JLabel();
        JTFServicioOtro06 = new javax.swing.JTextField();
        LblServicioOtro07 = new javax.swing.JLabel();
        JTFServicioOtro07 = new javax.swing.JTextField();
        LblServicioOtro08 = new javax.swing.JLabel();
        JTFServicioOtro08 = new javax.swing.JTextField();
        JSeparador05 = new javax.swing.JSeparator();
        LblPrecioServicio = new javax.swing.JLabel();
        JTFContenedorPrecio = new javax.swing.JTextField();
        LblInformativo = new javax.swing.JLabel();
        BtnRegistrarCita = new javax.swing.JButton();
        JSeparador06 = new javax.swing.JSeparator();
        BtnRetornar = new javax.swing.JButton();

        LblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        LblTitulo.setText("SERVICIO DE MANTENIMIENTO");

        LblSubtitulo.setText("Servicio de mantemiento dedicado para vehiculos Tesla:");

        LblSeleccionarModelo.setText("Seleccione el modelo del auto:");

        CbxSeleccionarTipoAuto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "TESLA", "OTRO VEHICULO" }));
        CbxSeleccionarTipoAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxSeleccionarTipoAutoActionPerformed(evt);
            }
        });

        LblNotaInformativa.setText("NOTA: La fecha puede ser modificada por el administrador de ser el caso.");

        LblCategoriaTesla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblCategoriaTesla.setText("VEHICULOS TESLA");

        LblServicioTesla01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblServicioTesla01.setText("Seleccione un servicio:");

        CbxServicioTesla01.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "SISTEMA DE REFRIGERACION", "SISTEMA ELECTRICO", "REVISION DE FRENOS", "REVISION DE BATERIA", "ITV" }));
        CbxServicioTesla01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxServicioTesla01ActionPerformed(evt);
            }
        });

        LblServicioTesla02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblServicioTesla02.setText("Numero de Motor:");

        LblServicioTesla03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblServicioTesla03.setText("Numero de serie del vehiculo:");

        LblServicioTesla04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblServicioTesla04.setText("Kilometraje Actual:");

        LblServicioTesla05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblServicioTesla05.setText("Observacion Adicional(Opcional):");

        LblServicioTesla06.setText("Fecha sugerida de Cita(YYYY-MM-DD):");

        LblCategoriaOtro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblCategoriaOtro.setText("OTROS VEHICULOS");

        LblServicioOtro01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblServicioOtro01.setText("Seleccione un servicio:");

        CbxServicioOtro01.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "MANTENIMIENTO GENERAL", "REVISION DE BATERIA", "CHEQUEO DE FRENOS", "INSPECCION ELECTRICA", "DIAGNOSTICO COMPLETO" }));
        CbxServicioOtro01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxServicioOtro01ActionPerformed(evt);
            }
        });

        LblServicioOtro02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblServicioOtro02.setText("Marca del Vehiculo:");

        LblServicioOtro03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblServicioOtro03.setText("Modelo del Vehiculo:");

        LblServicioOtro04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblServicioOtro04.setText("Año del Vehiculo:");

        JTFServicioOtro04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFServicioOtro04ActionPerformed(evt);
            }
        });

        LblServicioOtro05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblServicioOtro05.setText("Tipo de Motor:");

        LblServicioOtro06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblServicioOtro06.setText("Kilometraje del Vehiculo:");

        LblServicioOtro07.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblServicioOtro07.setText("Fecha sugerida de Cita(YYYY-MM-DD):");

        LblServicioOtro08.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblServicioOtro08.setText("Observacion Adicional (Opcional):");

        LblPrecioServicio.setText("PRECIO POR SERVICIO SELECCIONADO:");

        LblInformativo.setText("Una vez completados los campos, haga clic para registrar la operacion.");

        BtnRegistrarCita.setText("REGISTRAR CITA");
        BtnRegistrarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarCitaActionPerformed(evt);
            }
        });

        BtnRetornar.setText("RETORNAR");
        BtnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetornarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlContenedorGeneralLayout = new javax.swing.GroupLayout(PnlContenedorGeneral);
        PnlContenedorGeneral.setLayout(PnlContenedorGeneralLayout);
        PnlContenedorGeneralLayout.setHorizontalGroup(
            PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JSeparador06)
                    .addComponent(LblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JSeparador01)
                    .addComponent(JSeparador05)
                    .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                        .addComponent(BtnRetornar)
                        .addGap(58, 1088, Short.MAX_VALUE))
                    .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                        .addComponent(LblSeleccionarModelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CbxSeleccionarTipoAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LblNotaInformativa)
                        .addGap(63, 63, 63))
                    .addComponent(LblSubtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JSeparador02)
                    .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(LblCategoriaTesla, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(JSeparador03, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LblCategoriaOtro, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                            .addComponent(JSeparador04))
                        .addGap(35, 35, 35))
                    .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                                .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LblServicioTesla04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LblServicioTesla03, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTFServicioTesla03)
                                    .addComponent(JTFServicioTesla04)))
                            .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                                .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LblServicioTesla02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LblServicioTesla05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LblServicioTesla06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LblServicioTesla01, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CbxServicioTesla01, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JTFServicioTesla02)
                                    .addComponent(JTFServicioTesla05)
                                    .addComponent(JTFServicioTesla06, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PnlContenedorGeneralLayout.createSequentialGroup()
                                .addComponent(LblServicioOtro01)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CbxServicioOtro01, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PnlContenedorGeneralLayout.createSequentialGroup()
                                .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(LblServicioOtro03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LblServicioOtro02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LblServicioOtro04, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                                        .addComponent(JTFServicioOtro04)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LblServicioOtro05)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JTFServicioOtro05, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(JTFServicioOtro02)
                                    .addComponent(JTFServicioOtro03)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PnlContenedorGeneralLayout.createSequentialGroup()
                                .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LblServicioOtro06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LblServicioOtro07, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LblServicioOtro08, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTFServicioOtro08)
                                    .addComponent(JTFServicioOtro06)
                                    .addComponent(JTFServicioOtro07, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(66, 66, 66)))
                .addContainerGap())
            .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(LblPrecioServicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFContenedorPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                        .addComponent(LblInformativo)
                        .addGap(18, 18, 18)
                        .addComponent(BtnRegistrarCita)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlContenedorGeneralLayout.setVerticalGroup(
            PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblSubtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JSeparador01, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LblSeleccionarModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CbxSeleccionarTipoAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LblNotaInformativa)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JSeparador02, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblCategoriaTesla)
                    .addComponent(LblCategoriaOtro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JSeparador03, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(JSeparador04))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblServicioOtro01, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CbxServicioOtro01, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblServicioOtro02, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFServicioOtro02, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblServicioOtro03, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(JTFServicioOtro03, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblServicioOtro04, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFServicioOtro04, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblServicioOtro05, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFServicioOtro05))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblServicioOtro06, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFServicioOtro06, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblServicioOtro07, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFServicioOtro07, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblServicioOtro08, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFServicioOtro08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblServicioTesla01, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CbxServicioTesla01, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblServicioTesla02, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFServicioTesla02, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblServicioTesla03, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFServicioTesla03, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LblServicioTesla04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JTFServicioTesla04, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LblServicioTesla05, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PnlContenedorGeneralLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(JTFServicioTesla05, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblServicioTesla06, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFServicioTesla06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)))
                .addGap(18, 18, 18)
                .addComponent(JSeparador05, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPrecioServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JTFContenedorPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblInformativo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRegistrarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JSeparador06, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnRetornar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlContenedorGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlContenedorGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetornarActionPerformed
        mostrarPaneles(new panelInformativo());
    }//GEN-LAST:event_BtnRetornarActionPerformed

    private void CbxServicioTesla01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxServicioTesla01ActionPerformed
        CbxServicioTesla01.addActionListener(e -> actualizarPrecio());
    }//GEN-LAST:event_CbxServicioTesla01ActionPerformed

    private void actualizarEstadoCampos() {

        String tipo = String.valueOf(CbxSeleccionarTipoAuto.getSelectedItem());

        boolean esTesla = tipo.equals("TESLA");
        boolean esOtro = tipo.equals("OTRO VEHICULO");

        CbxServicioTesla01.setEnabled(esTesla);
        JTFServicioTesla02.setEnabled(esTesla);
        JTFServicioTesla03.setEnabled(esTesla);
        JTFServicioTesla04.setEnabled(esTesla);
        JTFServicioTesla05.setEnabled(esTesla);
        JTFServicioTesla06.setEnabled(esTesla);

        CbxServicioOtro01.setEnabled(esOtro);
        JTFServicioOtro02.setEnabled(esOtro);
        JTFServicioOtro03.setEnabled(esOtro);
        JTFServicioOtro04.setEnabled(esOtro);
        JTFServicioOtro05.setEnabled(esOtro);
        JTFServicioOtro06.setEnabled(esOtro);
        JTFServicioOtro07.setEnabled(esOtro);
        JTFServicioOtro08.setEnabled(esOtro);

        if (!esTesla && !esOtro) {
            JTFContenedorPrecio.setText("0.0");
        }
    }

    private void actualizarPrecio() {
        String tipo = String.valueOf(CbxSeleccionarTipoAuto.getSelectedItem());
        String srv = tipo.equals("TESLA")
                ? String.valueOf(CbxServicioTesla01.getSelectedItem())
                : String.valueOf(CbxServicioOtro01.getSelectedItem());

        double precio = 0.0;

        if (tipo.equals("TESLA")) {
            switch (srv) {
                case "SISTEMA DE REFRIGERACION":
                    precio = 510.0;
                    break;
                case "REVISION DE FRENOS":
                    precio = 420.50;
                    break;
                case "SISTEMA ELECTRICO":
                    precio = 690.00;
                    break;
                case "REVISION DE BATERIA":
                    precio = 900.00;
                    break;
                case "ITV":
                    precio = 1200.00;
                    break;
                default:
                    precio = 0.00;
                    break;
            }
        } else {
            switch (srv) {
                case "MANTENIMIENTO GENERAL":
                    precio = 210.00;
                    break;
                case "REVISION DE BATERIA":
                    precio = 120.50;
                    break;
                case "CHEQUEO DE FRENOS":
                    precio = 590.00;
                    break;
                case "INSPECCION ELECTRICA":
                    precio = 1900.00;
                    break;
                case "DIAGNOSTICO COMPLETO":
                    precio = 1400.00;
                    break;
                default:
                    precio = 0.00;
                    break;
            }
        }

        JTFContenedorPrecio.setText(String.format("%.2f", precio));
    }


    private void BtnRegistrarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarCitaActionPerformed

        try {
            ReservaServTres r = new ReservaServTres();
            r.setDniCliente(Sesion.clienteLogueado.getDNI_Cliente());
            r.setTipoVehiculo(CbxSeleccionarTipoAuto.getSelectedItem().toString());

            r.setServicioSolicitado(r.getTipoVehiculo().equals("TESLA") ? CbxServicioTesla01.getSelectedItem().toString() : CbxServicioOtro01.getSelectedItem().toString());

            String precioTxt = JTFContenedorPrecio.getText().trim();
            if (precioTxt.isEmpty()) {
                System.out.println("Error el precio esta vacio");
                return;
            }

            try {
                r.setPrecio(new BigDecimal(precioTxt));

            } catch (NumberFormatException ex) {
                System.out.println("Error, formato invalido." + ex.getMessage());
            }

            r.setFechaCita(LocalDate.parse(r.getTipoVehiculo().equals("TESLA") ? JTFServicioTesla06.getText() : JTFServicioOtro07.getText()));

            if (r.getTipoVehiculo().equals("TESLA")) {
                r.setNumeroMotor(JTFServicioTesla02.getText());
                r.setNumeroSerie(JTFServicioTesla03.getText());
                r.setKilometraje(!JTFServicioTesla04.getText().isBlank() ? Integer.parseInt(JTFServicioTesla04.getText()) : null);
                r.setObservacion(JTFServicioTesla05.getText());

            } else {
                r.setMarcaVehiculo(JTFServicioOtro02.getText());
                r.setModeloVehiculo(JTFServicioOtro03.getText());
                r.setAnioVehiculo(!JTFServicioOtro04.getText().isBlank() ? Integer.parseInt(JTFServicioOtro04.getText()) : null);

                r.setTipoMotor(JTFServicioOtro05.getText());
                r.setKilometraje(!JTFServicioOtro06.getText().isBlank() ? Integer.parseInt(JTFServicioOtro06.getText()) : null);
                r.setObservacion(JTFServicioOtro08.getText());
            }

            r.setDniEmpleado("2234589");

            new DAOReservaServTresIMPLEMENT().registrar(r);

            System.out.println("Se ha registrado la cita.");

        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }

        /*
             try {
            ReservaServTres r = new ReservaServTres();
            r.setDNI_Cliente(Sesion.clienteLogueado.getDNI_Cliente());
            r.setTipoVehiculo(CbxTipoAuto.getSelectedItem().toString());
            r.setPrecio(new BigDecimal(TxtPrecio.getText()));

            if (r.getTipoVehiculo().equals("TESLA")) {

            }

        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
         */

    }//GEN-LAST:event_BtnRegistrarCitaActionPerformed

    private void CbxSeleccionarTipoAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxSeleccionarTipoAutoActionPerformed
        actualizarPrecio();
        actualizarEstadoCampos();
    }//GEN-LAST:event_CbxSeleccionarTipoAutoActionPerformed

    private void CbxServicioOtro01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxServicioOtro01ActionPerformed
        CbxServicioOtro01.addActionListener(e -> actualizarPrecio());
    }//GEN-LAST:event_CbxServicioOtro01ActionPerformed

    private void JTFServicioOtro04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFServicioOtro04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFServicioOtro04ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistrarCita;
    private javax.swing.JButton BtnRetornar;
    private javax.swing.JComboBox<String> CbxSeleccionarTipoAuto;
    private javax.swing.JComboBox<String> CbxServicioOtro01;
    private javax.swing.JComboBox<String> CbxServicioTesla01;
    private javax.swing.JSeparator JSeparador01;
    private javax.swing.JSeparator JSeparador02;
    private javax.swing.JSeparator JSeparador03;
    private javax.swing.JSeparator JSeparador04;
    private javax.swing.JSeparator JSeparador05;
    private javax.swing.JSeparator JSeparador06;
    private javax.swing.JTextField JTFContenedorPrecio;
    private javax.swing.JTextField JTFServicioOtro02;
    private javax.swing.JTextField JTFServicioOtro03;
    private javax.swing.JTextField JTFServicioOtro04;
    private javax.swing.JTextField JTFServicioOtro05;
    private javax.swing.JTextField JTFServicioOtro06;
    private javax.swing.JTextField JTFServicioOtro07;
    private javax.swing.JTextField JTFServicioOtro08;
    private javax.swing.JTextField JTFServicioTesla02;
    private javax.swing.JTextField JTFServicioTesla03;
    private javax.swing.JTextField JTFServicioTesla04;
    private javax.swing.JTextField JTFServicioTesla05;
    private javax.swing.JTextField JTFServicioTesla06;
    private javax.swing.JLabel LblCategoriaOtro;
    private javax.swing.JLabel LblCategoriaTesla;
    private javax.swing.JLabel LblInformativo;
    private javax.swing.JLabel LblNotaInformativa;
    private javax.swing.JLabel LblPrecioServicio;
    private javax.swing.JLabel LblSeleccionarModelo;
    private javax.swing.JLabel LblServicioOtro01;
    private javax.swing.JLabel LblServicioOtro02;
    private javax.swing.JLabel LblServicioOtro03;
    private javax.swing.JLabel LblServicioOtro04;
    private javax.swing.JLabel LblServicioOtro05;
    private javax.swing.JLabel LblServicioOtro06;
    private javax.swing.JLabel LblServicioOtro07;
    private javax.swing.JLabel LblServicioOtro08;
    private javax.swing.JLabel LblServicioTesla01;
    private javax.swing.JLabel LblServicioTesla02;
    private javax.swing.JLabel LblServicioTesla03;
    private javax.swing.JLabel LblServicioTesla04;
    private javax.swing.JLabel LblServicioTesla05;
    private javax.swing.JLabel LblServicioTesla06;
    private javax.swing.JLabel LblSubtitulo;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JPanel PnlContenedorGeneral;
    // End of variables declaration//GEN-END:variables
}
