/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InformativePanels;

import Panels.panelInformativo;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Fabrizio
 */
public class Informativo06 extends javax.swing.JPanel {

    /**
     * Creates new form Informativo06
     */
    public Informativo06() {
        initComponents();
    }

    public void mostraPaneles(JPanel panel) {
        panel.setSize(1194, 694);
        panel.setLocation(0, 0);

        PanelContendor.removeAll();
        PanelContendor.add(panel, BorderLayout.CENTER);
        PanelContendor.revalidate();
        PanelContendor.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContendor = new javax.swing.JPanel();
        TxtTitulo = new javax.swing.JLabel();
        TxtInformativo01 = new javax.swing.JLabel();
        Separador01 = new javax.swing.JSeparator();
        TxtInformativo02 = new javax.swing.JLabel();
        TxtInformativo03 = new javax.swing.JLabel();
        TxtInformativo04 = new javax.swing.JLabel();
        TxtInformativo05 = new javax.swing.JLabel();
        Separador02 = new javax.swing.JSeparator();
        TxtInformativo06 = new javax.swing.JLabel();
        TxtInformativo07 = new javax.swing.JLabel();
        TxtInformativo08 = new javax.swing.JLabel();
        TxtInformativo09 = new javax.swing.JLabel();
        Separador03 = new javax.swing.JSeparator();
        TxtInformativo10 = new javax.swing.JLabel();
        TxtInformativo11 = new javax.swing.JLabel();
        BtnRetornar = new javax.swing.JButton();

        TxtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        TxtTitulo.setText("AÑO 2017 | PRESENTACION TESLA SEMI Y ROADSTER II");

        TxtInformativo01.setText("En un evento doble, Tesla sorprende con dos nuevos vehículos revolucionarios.");

        TxtInformativo02.setText("· TESLA SEMI:");

        TxtInformativo03.setText("- Camión eléctrico para transporte de carga.");

        TxtInformativo04.setText(" - Autonomía: hasta 800 km.");

        TxtInformativo05.setText("- Menor coste operativo vs. camiones diésel.");

        TxtInformativo06.setText("· ROADSTER 2da GENERACION:");

        TxtInformativo07.setText("- Aceleración: 0-100 km/h en 1.9 seg.");

        TxtInformativo08.setText("- Velocidad Máxima: +400 km/h.");

        TxtInformativo09.setText("- Autonomía estimada: 1000 km.");

        TxtInformativo10.setText("DATO CURIOSO:");

        TxtInformativo11.setText("- Evento impactante que proyectó a Tesla hacia nuevos mercados.");

        BtnRetornar.setText("RETORNAR");
        BtnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetornarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelContendorLayout = new javax.swing.GroupLayout(PanelContendor);
        PanelContendor.setLayout(PanelContendorLayout);
        PanelContendorLayout.setHorizontalGroup(
            PanelContendorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContendorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelContendorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtTitulo)
                    .addComponent(TxtInformativo02)
                    .addComponent(TxtInformativo03)
                    .addComponent(TxtInformativo04)
                    .addComponent(TxtInformativo05)
                    .addComponent(TxtInformativo06)
                    .addComponent(TxtInformativo07)
                    .addComponent(TxtInformativo08)
                    .addComponent(TxtInformativo09)
                    .addGroup(PanelContendorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Separador03, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Separador02, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Separador01, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TxtInformativo01, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(TxtInformativo10)
                    .addComponent(TxtInformativo11))
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelContendorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnRetornar)
                .addContainerGap())
        );
        PanelContendorLayout.setVerticalGroup(
            PanelContendorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContendorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtInformativo01)
                .addGap(18, 18, 18)
                .addComponent(Separador01, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtInformativo02)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtInformativo03)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtInformativo04)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtInformativo05)
                .addGap(18, 18, 18)
                .addComponent(Separador02, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtInformativo06)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtInformativo07)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtInformativo08)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtInformativo09)
                .addGap(18, 18, 18)
                .addComponent(Separador03, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtInformativo10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtInformativo11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addComponent(BtnRetornar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContendor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContendor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetornarActionPerformed
        mostraPaneles(new panelInformativo());
    }//GEN-LAST:event_BtnRetornarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRetornar;
    private javax.swing.JPanel PanelContendor;
    private javax.swing.JSeparator Separador01;
    private javax.swing.JSeparator Separador02;
    private javax.swing.JSeparator Separador03;
    private javax.swing.JLabel TxtInformativo01;
    private javax.swing.JLabel TxtInformativo02;
    private javax.swing.JLabel TxtInformativo03;
    private javax.swing.JLabel TxtInformativo04;
    private javax.swing.JLabel TxtInformativo05;
    private javax.swing.JLabel TxtInformativo06;
    private javax.swing.JLabel TxtInformativo07;
    private javax.swing.JLabel TxtInformativo08;
    private javax.swing.JLabel TxtInformativo09;
    private javax.swing.JLabel TxtInformativo10;
    private javax.swing.JLabel TxtInformativo11;
    private javax.swing.JLabel TxtTitulo;
    // End of variables declaration//GEN-END:variables
}
